<?php
/**
 * Liqpay Payment Module
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category        Liqpay
 * @package         Liqpay
 * @version         0.0.1
 * @author          Liqpay
 * @copyright       Copyright (c) 2014 Liqpay
 * @license         http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 *
 * EXTENSION INFORMATION
 *
 * LIQPAY API       https://www.liqpay.com/ru/doc
 *
 */
?>

<?php $idForm = 'liqpay_'.md5(time()); ?>

<form method="post" action="<?=$action?>" id="<?=$idForm?>">
  <?php foreach ($sendData as $name => $value): ?>
  <input type="hidden" name="<?=$name?>" value="<?=$value?>" />
  <?php endforeach; ?>

  <?php if ($payButton): ?>
  <input type="image" src="//static.liqpay.com/buttons/p1<?=$language?>.radius.png" name="btn_text" />
  <?php endif; ?>

  <?php if ($autoSend): ?>
  <script>document.getElementById("<?=$idForm?>").submit();</script>
  <?php endif; ?>
</form>